---
roles:
  posix_noagent:
    private_networks:
      - {ip: '0.0.0.0', auto_network: true}
    provisioners:
      - {type: shell, inline: "echo 'nameserver 8.8.8.8' > /etc/resolv.conf"}
      - {type: hosts}
